Bug Fix
I was getting the following error:

```
docker-compose -f compose.yml build
ERROR: Validation failed in file './compose.yml', reason(s):
server.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
server.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
server.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
server.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
server.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
server.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
server.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
server.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
```

To map ports u need to use "ports" instead of expose.